function NewTab(link) {
    window.open(link, "_blank");
}

class Celebrity {
  constructor(name, source_image, party, link) {
    this.name = name;
    this.src = source_image;
    this.party = party;
    this.link = link;
  }

  render(){
    return `<div class="col" onclick="NewTab('${this.link}');"><div class="position-relative gallery-item" style="cursor: pointer;"><img src=${this.src} alt="${this.name}" class="${this.party}"></div></div>`;
  }
}

class Democrat extends Celebrity {
  constructor(name, source_image, link) {
    super(name, source_image, "democrat", link);
    if (link.length == 0)
      this.link = "https://en.wikipedia.org/wiki/List_of_Kamala_Harris_2024_presidential_campaign_non-political_endorsements";
  }
}

class Republican extends Celebrity {
  constructor(name, source_image, link) {
    super(name, source_image, "republican", link);
    if (link.length == 0)
      this.link = "https://en.wikipedia.org/wiki/List_of_Donald_Trump_2024_presidential_campaign_non-political_endorsements";
  }
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function add_celebrities_to_container(celebrities, image_container_id){
  let container = document.getElementById(image_container_id);
  for (let i = 0; i < celebrities.length; i++) {
    container.innerHTML += celebrities[i].render();
    await sleep(50);
  }
}

// Add Celebrities Supporting Democratic Party into this array
// Democrat(Name, PhotoLink, ReferenceLink)
let democrats = [
  new Democrat("Leonardo DiCaprio", "./photos/leonardo_dicaprio.jpg", "https://apnews.com/article/leonardo-dicaprio-endorses-kamala-harris-election-2024-40bf7286e7219dfd59957bf28d34f578"),
  new Democrat("Oprah Winfrey", "./photos/Oprah_Winfrey.jpg", "https://www.aljazeera.com/news/2024/9/20/oprahs-kamala-harris-fundraiser-does-her-support-swing-elections"),
  new Democrat("Taylor Swift", "./photos/taylor_swift.jpg", "https://www.nbcnews.com/politics/2024-election/taylor-swift-endorses-kamala-harris-rcna170547"),
  new Democrat("Jon Bon Jovi", "./photos/Jon_Bon_Jovi.jpg", "https://www.billboard.com/music/rock/jon-bon-jovi-endorsement-kamala-harris-president-truth-matters-1235800897/"),
  new Democrat("Meryl Streep", "./photos/Meryl_Streep.jpg", "https://ew.com/meryl-streep-accidentally-calls-kamala-harris-president-8716127"),
  new Democrat("Robert De Niro", "./photos/Robert_De_Niro.jpg", "https://www.hollywoodreporter.com/news/general-news/robert-de-niro-presidential-election-kamala-harris-donald-trump-1235995206/"),
  new Democrat("Katy Perry", "./photos/Katy_Perry.jpg", "https://www.dailymail.co.uk/tvshowbiz/article-13840491/Katy-Perry-support-Kamala-Harris-NYC-Taylor-Swift-endorsement.html"),
  new Democrat("Rihanna", "./photos/Rihanna.jpg", "https://www.vogue.com/article/celebrities-who-have-endorsed-kamala-harris-for-president"),
  new Democrat("Ariana Grande", "./photos/Ariana_Grande.jpg", "https://www.dailymail.co.uk/news/article-14010309/Ariana-Grande-backs-Kamala-Harris-followers-voted-her.html"),
  new Democrat("Jimmy Fallon", "./photos/Jimmy_Fallon.jpg", "https://www.huffpost.com/entry/jimmy-fallon-kamala-harris-rattle-trump_n_66d81ff7e4b0688475d8fe54"),
  new Democrat("Michelle Obama", "./photos/Michelle_Obama.jpg", "https://www.washingtonpost.com/politics/2024/10/26/michelle-obama-campaigns-kamala-harris/"),
  new Democrat("Beyoncé", "./photos/Beyonce.jpg", "https://www.bbc.com/news/videos/cz9xpzeqq4po"),
  new Democrat("Ben Stiller", "./photos/Ben_Stiller.jpg", "https://www.youtube.com/watch?v=YnaUBhfPh58"),
  new Democrat("Sarah Jessica Parker", "./photos/Sarah_Jessica_Parker.jpg", "https://www.independent.co.uk/arts-entertainment/tv/news/sarah-jessica-parker-kamala-harris-presidential-election-b2635135.html"),
  new Democrat("Amy Schumer", "./photos/Amy_Schumer.jpg", "https://www.facebook.com/photo.php?fbid=1031536251664545&id=100044245398455&set=a.234472748037570"),
  new Democrat("Kerry Washington", "./photos/Kerry_Washington.jpg", "https://www.usatoday.com/story/news/politics/elections/2024/10/28/kerry-washington-kamala-harris-olivia-pope-wisconsin/75885917007/"),
  new Democrat("Olivia Wilde", "./photos/Olivia_Wilde.jpg", "https://en.wikipedia.org/wiki/List_of_Kamala_Harris_2024_presidential_campaign_non-political_endorsements"),
  new Democrat("Shonda Rhimes", "./photos/Shonda_Rhimes.jpg", "https://en.wikipedia.org/wiki/List_of_Kamala_Harris_2024_presidential_campaign_non-political_endorsements"),
  new Democrat("Jensen Ackles", "./photos/Jensen_Ackles.jpg", ""),
  new Democrat("Nick Adams", "./photos/Nick_Adams.jpg", ""),
  new Democrat("Uzo Aduba", "./photos/Uzo_Aduba.jpg", ""),
  new Democrat("Jessica Alba", "./photos/Jessica_Alba.jpg", ""),
  new Democrat("Jason Alexander", "./photos/Jason_Alexander.jpg", ""),
  new Democrat("Tatyana Ali", "./photos/Tatyana_Ali.jpg", ""),
  new Democrat("Debbie Allen", "./photos/Debbie_Allen.jpg", ""),
  new Democrat("Laz Alonso", "./photos/Laz_Alonso.jpg", ""),
  new Democrat("Utkarsh Ambudkar", "./photos/Utkarsh_Ambudkar.jpg", ""),
  new Democrat("Anthony Anderson", "./photos/Anthony_Anderson.jpg", ""),
  new Democrat("Jennifer Aniston", "./photos/Jennifer_Aniston.jpg", ""),
  new Democrat("Jonathan Del Arco", "./photos/Jonathan_Del_Arco.jpg", ""),
  new Democrat("Iain Armitage", "./photos/Iain_Armitage.jpg", ""),
  new Democrat("Sean Astin", "./photos/Sean_Astin.jpg", ""),
  new Democrat("Yetide Badaki", "./photos/Yetide_Badaki.jpg", ""),
  new Democrat("Diedrich Bader", "./photos/Diedrich_Bader.jpg", ""),
  new Democrat("Elizabeth Banks", "./photos/Elizabeth_Banks.jpg", ""),
  new Democrat("Christine Baranski", "./photos/Christine_Baranski.jpg", ""),
  new Democrat("Ike Barinholtz", "./photos/Ike_Barinholtz.jpg", ""),
  new Democrat("Todd Barry", "./photos/Todd_Barry.jpg", ""),
  new Democrat("Jason Bateman", "./photos/Jason_Bateman.jpg", ""),
  new Democrat("Bryan Batt", "./photos/Bryan_Batt.jpg", ""),
  new Democrat("Dave Bautista", "./photos/Dave_Bautista.jpg", ""),
  new Democrat("Shoshana Bean", "./photos/Shoshana_Bean.jpg", ""),
  new Democrat("Garcelle Beauvais", "./photos/Garcelle_Beauvais.jpg", ""),
  new Democrat("Lake Bell", "./photos/Lake_Bell.jpg", ""),
  new Democrat("Laura Benanti", "./photos/Laura_Benanti.jpg", ""),
  new Democrat("Paul Bettany", "./photos/Paul_Bettany.jpg", ""),
  new Democrat("Anjali Bhimani", "./photos/Anjali_Bhimani.jpg", ""),
  new Democrat("Esmé Bianco", "./photos/Esmé_Bianco.jpg", ""),
  new Democrat("Alexandra Billings", "./photos/Alexandra_Billings.jpg", ""),
  new Democrat("Matt Bomer", "./photos/Matt_Bomer.jpg", ""),
  new Democrat("Lorraine Bracco", "./photos/Lorraine_Bracco.jpg", ""),
  new Democrat("Eric Braeden", "./photos/Eric_Braeden.jpg", ""),
  new Democrat("Sufe Bradshaw", "./photos/Sufe_Bradshaw.jpg", ""),
  new Democrat("Jeff Bridges", "./photos/Jeff_Bridges.jpg", ""),
  new Democrat("Christie Brinkley", "./photos/Christie_Brinkley.jpg", ""),
  new Democrat("Connie Britton", "./photos/Connie_Britton.jpg", ""),
  new Democrat("Mel Brooks", "./photos/Mel_Brooks.jpg", ""),
  new Democrat("Rachel Brosnahan", "./photos/Rachel_Brosnahan.jpg", ""),
  new Democrat("Sterling K. Brown", "./photos/Sterling_K._Brown.jpg", ""),
  new Democrat("Yvette Nicole Brown", "./photos/Yvette_Nicole_Brown.jpg", ""),
  new Democrat("Quinta Brunson", "./photos/Quinta_Brunson.jpg", ""),
  new Democrat("Dan Bucatinsky", "./photos/Dan_Bucatinsky.jpg", ""),
  new Democrat("Betty Buckley", "./photos/Betty_Buckley.jpg", ""),
  new Democrat("Laura Bell Bundy", "./photos/Laura_Bell_Bundy.jpg", ""),
  new Democrat("LeVar Burton", "./photos/LeVar_Burton.jpg", ""),
  new Democrat("Steve Buscemi", "./photos/Steve_Buscemi.jpg", ""),
  new Democrat("Sophia Bush", "./photos/Sophia_Bush.jpg", ""),
  new Democrat("Jaime Camil", "./photos/Jaime_Camil.jpg", ""),
  new Democrat("Lynda Carter", "./photos/Lynda_Carter.jpg", ""),
  new Democrat("Osric Chau", "./photos/Osric_Chau.jpg", ""),
  new Democrat("Don Cheadle", "./photos/Don_Cheadle.jpg", ""),
  new Democrat("Kristin Chenoweth", "./photos/Kristin_Chenoweth.jpg", ""),
  new Democrat("Mary Chieffo", "./photos/Mary_Chieffo.jpg", ""),
  new Democrat("Anna Chlumsky", "./photos/Anna_Chlumsky.jpg", ""),
  new Democrat("Victoria Clark", "./photos/Victoria_Clark.jpg", ""),
  new Democrat("John Cleese", "./photos/John_Cleese.jpg", ""),
  new Democrat("George Clooney", "./photos/George_Clooney.jpg", ""),
  new Democrat("Glenn Close", "./photos/Glenn_Close.jpg", ""),
  new Democrat("Jennifer Cody", "./photos/Jennifer_Cody.jpg", ""),
  new Democrat("Gary Cole", "./photos/Gary_Cole.jpg", ""),
  new Democrat("Jenn Colella", "./photos/Jenn_Colella.jpg", ""),
  new Democrat("Lily Collins", "./photos/Lily_Collins.jpg", ""),
  new Democrat("Misha Collins", "./photos/Misha_Collins.jpg", ""),
  new Democrat("Adam Conover", "./photos/Adam_Conover.jpg", ""),
  new Democrat("Jennifer Coolidge", "./photos/Jennifer_Coolidge.jpg", ""),
  new Democrat("Lilli Cooper", "./photos/Lilli_Cooper.jpg", ""),
  new Democrat("Lorna Courtney", "./photos/Lorna_Courtney.jpg", ""),
  new Democrat("Laverne Cox", "./photos/Laverne_Cox.jpg", ""),
  new Democrat("Bryan Cranston", "./photos/Bryan_Cranston.jpg", ""),
  new Democrat("Chace Crawford", "./photos/Chace_Crawford.jpg", ""),
  new Democrat("Darren Criss", "./photos/Darren_Criss.jpg", ""),
  new Democrat("Denise Crosby", "./photos/Denise_Crosby.jpg", ""),
  new Democrat("Wilson Cruz", "./photos/Wilson_Cruz.jpg", ""),
  new Democrat("Jon Cryer", "./photos/Jon_Cryer.jpg", ""),
  new Democrat("Alan Cumming", "./photos/Alan_Cumming.jpg", ""),
  new Democrat("Ayesha Curry", "./photos/Ayesha_Curry.jpg", ""),
  new Democrat("Valorie Curry", "./photos/Valorie_Curry.jpg", ""),
  new Democrat("Jane Curtin", "./photos/Jane_Curtin.jpg", ""),
  new Democrat("Jamie Lee Curtis", "./photos/Jamie_Lee_Curtis.jpg", ""),
  new Democrat("John Cusack", "./photos/John_Cusack.jpg", ""),
  new Democrat("Tim Daly", "./photos/Tim_Daly.jpg", ""),
  new Democrat("Matt Damon", "./photos/Matt_Damon.jpg", ""),
  new Democrat("William Daniels", "./photos/William_Daniels.jpg", ""),
  new Democrat("Ted Danson", "./photos/Ted_Danson.jpg", ""),
  new Democrat("Kristin Davis", "./photos/Kristin_Davis.jpg", ""),
  new Democrat("Viola Davis", "./photos/Viola_Davis.jpg", ""),
  new Democrat("Rosario Dawson", "./photos/Rosario_Dawson.jpg", ""),
  new Democrat("Felicia Day", "./photos/Felicia_Day.jpg", ""),
  new Democrat("Elizabeth Dennehy", "./photos/Elizabeth_Dennehy.jpg", ""),
  new Democrat("Guillermo Díaz", "./photos/Guillermo_Díaz.jpg", ""),
  new Democrat("Colman Domingo", "./photos/Colman_Domingo.jpg", ""),
  new Democrat("Robert Downey Jr.", "./photos/Robert_Downey_Jr..jpg", ""),
  new Democrat("Fran Drescher", "./photos/Fran_Drescher.jpg", ""),
  new Democrat("David Duchovny", "./photos/David_Duchovny.jpg", ""),
  new Democrat("Hilary Duff", "./photos/Hilary_Duff.jpg", ""),
  new Democrat("Clea DuVall", "./photos/Clea_DuVall.jpg", ""),
  new Democrat("Michael Ealy", "./photos/Michael_Ealy.jpg", ""),
  new Democrat("Billy Eichner", "./photos/Billy_Eichner.jpg", ""),
  new Democrat("Sam Elliott", "./photos/Sam_Elliott.jpg", ""),
  new Democrat("Raúl Esparza", "./photos/Raúl_Esparza.jpg", ""),
  new Democrat("Eden Espinosa", "./photos/Eden_Espinosa.jpg", ""),
  new Democrat("Chris Evans", "./photos/Chris_Evans.jpg", ""),
  new Democrat("Morgan Fairchild", "./photos/Morgan_Fairchild.jpg", ""),
  new Democrat("Terry Farrell", "./photos/Terry_Farrell.jpg", ""),
  new Democrat("Jesse Tyler Ferguson", "./photos/Jesse_Tyler_Ferguson.jpg", ""),
  new Democrat("Will Ferrell", "./photos/Will_Ferrell.jpg", ""),
  new Democrat("America Ferrera", "./photos/America_Ferrera.jpg", ""),
  new Democrat("Sally Field", "./photos/Sally_Field.jpg", ""),
  new Democrat("Scott Foley", "./photos/Scott_Foley.jpg", ""),
  new Democrat("Jane Fonda", "./photos/Jane_Fonda.jpg", ""),
  new Democrat("Karen Fukuhara", "./photos/Karen_Fukuhara.jpg", ""),
  new Democrat("Josh Gad", "./photos/Josh_Gad.jpg", ""),
  new Democrat("Megan Gallagher", "./photos/Megan_Gallagher.jpg", ""),
  new Democrat("Jennifer Garner", "./photos/Jennifer_Garner.jpg", ""),
  new Democrat("Ana Gasteyer", "./photos/Ana_Gasteyer.jpg", ""),
  new Democrat("Jason Winston George", "./photos/Jason_Winston_George.jpg", ""),
  new Democrat("Kaia Gerber ", "./photos/Kaia_Gerber_.jpg", ""),
  new Democrat("J. Harrison Ghee", "./photos/J._Harrison_Ghee.jpg", ""),
  new Democrat("Paul Giamatti", "./photos/Paul_Giamatti.jpg", ""),
  new Democrat("Tony Goldwyn", "./photos/Tony_Goldwyn.jpg", ""),
  new Democrat("Nicholas Gonzalez", "./photos/Nicholas_Gonzalez.jpg", ""),
  new Democrat("Joseph Gordon-Levitt", "./photos/Joseph_Gordon-Levitt.jpg", ""),
  new Democrat("Max Greenfield", "./photos/Max_Greenfield.jpg", ""),
  new Democrat("Blake Cooper Griffin", "./photos/Blake_Cooper_Griffin.jpg", ""),
  new Democrat("Danai Gurira", "./photos/Danai_Gurira.jpg", ""),
  new Democrat("Kathryn Hahn", "./photos/Kathryn_Hahn.jpg", ""),
  new Democrat("Tony Hale", "./photos/Tony_Hale.jpg", ""),
  new Democrat("Mark Hamill", "./photos/Mark_Hamill.jpg", ""),
  new Democrat("Jon Hamm", "./photos/Jon_Hamm.jpg", ""),
  new Democrat("Tom Hanks", "./photos/Tom_Hanks.jpg", ""),
  new Democrat("Mariska Hargitay", "./photos/Mariska_Hargitay.jpg", ""),
  new Democrat("Hill Harper", "./photos/Hill_Harper.jpg", ""),
  new Democrat("Jackée Harry", "./photos/Jackée_Harry.jpg", ""),
  new Democrat("Anne Hathaway", "./photos/Anne_Hathaway.jpg", ""),
  new Democrat("Ethan Hawke", "./photos/Ethan_Hawke.jpg", ""),
  new Democrat("Tim Heidecker", "./photos/Tim_Heidecker.jpg", ""),
  new Democrat("Ed Helms", "./photos/Ed_Helms.jpg", ""),
  new Democrat("Erika Henningsen", "./photos/Erika_Henningsen.jpg", ""),
  new Democrat("Catherine Hicks", "./photos/Catherine_Hicks.jpg", ""),
  new Democrat("Dulé Hill", "./photos/Dulé_Hill.jpg", ""),
  new Democrat("Ashley Hinshaw", "./photos/Ashley_Hinshaw.jpg", ""),
  new Democrat("Katie Holmes", "./photos/Katie_Holmes.jpg", ""),
  new Democrat("Vanessa Hudgens", "./photos/Vanessa_Hudgens.jpg", ""),
  new Democrat("Michelle Hurd", "./photos/Michelle_Hurd.jpg", ""),
  new Democrat("James Monroe Iglehart", "./photos/James_Monroe_Iglehart.jpg", ""),
  new Democrat("Michael Imperioli", "./photos/Michael_Imperioli.jpg", ""),
  new Democrat("Erika Ishii", "./photos/Erika_Ishii.jpg", ""),
  new Democrat("Aabria Iyengar", "./photos/Aabria_Iyengar.jpg", ""),
  new Democrat("Samuel L. Jackson", "./photos/Samuel_L._Jackson.jpg", ""),
  new Democrat("Arielle Jacobs", "./photos/Arielle_Jacobs.jpg", ""),
  new Democrat("Poorna Jagannathan", "./photos/Poorna_Jagannathan.jpg", ""),
  new Democrat("Nikki M. James", "./photos/Nikki_M._James.jpg", ""),
  new Democrat("Allison Janney", "./photos/Allison_Janney.jpg", ""),
  new Democrat("Ken Jeong", "./photos/Ken_Jeong.jpg", ""),
  new Democrat("Maz Jobrani", "./photos/Maz_Jobrani.jpg", ""),
  new Democrat("Scarlett Johansson", "./photos/Scarlett_Johansson.jpg", ""),
  new Democrat("Claudia Jordan", "./photos/Claudia_Jordan.jpg", ""),
  new Democrat("Jeremy Jordan", "./photos/Jeremy_Jordan.jpg", ""),
  new Democrat("Ashley Judd", "./photos/Ashley_Judd.jpg", ""),
  new Democrat("Mindy Kaling", "./photos/Mindy_Kaling.jpg", ""),
  new Democrat("Michael Keaton", "./photos/Michael_Keaton.jpg", ""),
  new Democrat("Michael Kelly", "./photos/Michael_Kelly.jpg", ""),
  new Democrat("Keegan-Michael Key", "./photos/Keegan-Michael_Key.jpg", ""),
  new Democrat("Daniel Dae Kim", "./photos/Daniel_Dae_Kim.jpg", ""),
  new Democrat("Boris Kodjoe", "./photos/Boris_Kodjoe.jpg", ""),
  new Democrat("David Koechner", "./photos/David_Koechner.jpg", ""),
  new Democrat("Liza Koshy", "./photos/Liza_Koshy.jpg", ""),
  new Democrat("Shin Koyamada", "./photos/Shin_Koyamada.jpg", ""),
  new Democrat("Judy Kuhn", "./photos/Judy_Kuhn.jpg", ""),
  new Democrat("LaChanze", "./photos/LaChanze.jpg", ""),
  new Democrat("Jennifer Lawrence", "./photos/Jennifer_Lawrence.jpg", ""),
  new Democrat("Raymond Lee", "./photos/Raymond_Lee.jpg", ""),
  new Democrat("John Leguizamo", "./photos/John_Leguizamo.jpg", ""),
  new Democrat("Thomas Lennon", "./photos/Thomas_Lennon.jpg", ""),
  new Democrat("Telly Leung", "./photos/Telly_Leung.jpg", ""),
  new Democrat("Dawnn Lewis", "./photos/Dawnn_Lewis.jpg", ""),
  new Democrat("Jenifer Lewis", "./photos/Jenifer_Lewis.jpg", ""),
  new Democrat("Matthew Lillard", "./photos/Matthew_Lillard.jpg", ""),
  new Democrat("Blake Lively", "./photos/Blake_Lively.jpg", ""),
  new Democrat("Eva Longoria", "./photos/Eva_Longoria.jpg", ""),
  new Democrat("Julia Louis-Dreyfus", "./photos/Julia_Louis-Dreyfus.jpg", ""),
  new Democrat("Katie Lowes", "./photos/Katie_Lowes.jpg", ""),
  new Democrat("Patti LuPone", "./photos/Patti_LuPone.jpg", ""),
  new Democrat("Natasha Lyonne", "./photos/Natasha_Lyonne.jpg", ""),
  new Democrat("Tzi Ma", "./photos/Tzi_Ma.jpg", ""),
  new Democrat("Joshua Malina", "./photos/Joshua_Malina.jpg", ""),
  new Democrat("Chase Masterson", "./photos/Chase_Masterson.jpg", ""),
  new Democrat("Mary McCormack", "./photos/Mary_McCormack.jpg", ""),
  new Democrat("Audra McDonald", "./photos/Audra_McDonald.jpg", ""),
  new Democrat("Gates McFadden", "./photos/Gates_McFadden.jpg", ""),
  new Democrat("Joel McHale", "./photos/Joel_McHale.jpg", ""),
  new Democrat("Christopher Meloni", "./photos/Christopher_Meloni.jpg", ""),
  new Democrat("Idina Menzel", "./photos/Idina_Menzel.jpg", ""),
  new Democrat("Andy Merrill", "./photos/Andy_Merrill.jpg", ""),
  new Democrat("Chris Messina", "./photos/Chris_Messina.jpg", ""),
  new Democrat("Bette Midler", "./photos/Bette_Midler.jpg", ""),
  new Democrat("Alyssa Milano", "./photos/Alyssa_Milano.jpg", ""),
  new Democrat("Lin-Manuel Miranda", "./photos/Lin-Manuel_Miranda.jpg", ""),
  new Democrat("Matthew Modine", "./photos/Matthew_Modine.jpg", ""),
  new Democrat("Demi Moore", "./photos/Demi_Moore.jpg", ""),
  new Democrat("Julianne Moore", "./photos/Julianne_Moore.jpg", ""),
  new Democrat("Rita Moreno", "./photos/Rita_Moreno.jpg", ""),
  new Democrat("Chloë Grace Moretz", "./photos/Chloë_Grace_Moretz.jpg", ""),
  new Democrat("Erin Moriarty", "./photos/Erin_Moriarty.jpg", ""),
  new Democrat("Kate Mulgrew", "./photos/Kate_Mulgrew.jpg", ""),
  new Democrat("Kathy Najimy", "./photos/Kathy_Najimy.jpg", ""),
  new Democrat("Aparna Nancherla", "./photos/Aparna_Nancherla.jpg", ""),
  new Democrat("Niecy Nash", "./photos/Niecy_Nash.jpg", ""),
  new Democrat("Shakina Nayfack", "./photos/Shakina_Nayfack.jpg", ""),
  new Democrat("George Newbern", "./photos/George_Newbern.jpg", ""),
  new Democrat("Cynthia Nixon", "./photos/Cynthia_Nixon.jpg", ""),
  new Democrat("Dean Norris", "./photos/Dean_Norris.jpg", ""),
  new Democrat("Lupita Nyong'o", "./photos/Lupita_Nyong'o.jpg", ""),
  new Democrat("Nick Offerman", "./photos/Nick_Offerman.jpg", ""),
  new Democrat("Kelli O'Hara", "./photos/Kelli_O'Hara.jpg", ""),
  new Democrat("Edward James Olmos", "./photos/Edward_James_Olmos.jpg", ""),
  new Democrat("Rory O'Malley", "./photos/Rory_O'Malley.jpg", ""),
  new Democrat("Tatum O'Neal", "./photos/Tatum_O'Neal.jpg", ""),
  new Democrat("Ed O'Neill", "./photos/Ed_O'Neill.jpg", ""),
  new Democrat("Maulik Pancholy", "./photos/Maulik_Pancholy.jpg", ""),
  new Democrat("Ashley Park", "./photos/Ashley_Park.jpg", ""),
  new Democrat("Linda Park", "./photos/Linda_Park.jpg", ""),
  new Democrat("Nicole Ari Parker", "./photos/Nicole_Ari_Parker.jpg", ""),
  new Democrat("Mandy Patinkin", "./photos/Mandy_Patinkin.jpg", ""),
  new Democrat("Lauren Patten", "./photos/Lauren_Patten.jpg", ""),
  new Democrat("Sarah Paulson", "./photos/Sarah_Paulson.jpg", ""),
  new Democrat("Holly Robinson Peete", "./photos/Holly_Robinson_Peete.jpg", ""),
  new Democrat("Piper Perabo", "./photos/Piper_Perabo.jpg", ""),
  new Democrat("Rosie Perez", "./photos/Rosie_Perez.jpg", ""),
  new Democrat("Pauley Perrette", "./photos/Pauley_Perrette.jpg", ""),
  new Democrat("Jeff Perry", "./photos/Jeff_Perry.jpg", ""),
  new Democrat("Tyler Perry", "./photos/Tyler_Perry.jpg", ""),
  new Democrat("Valarie Pettiford", "./photos/Valarie_Pettiford.jpg", ""),
  new Democrat("Michelle Pfeiffer", "./photos/Michelle_Pfeiffer.jpg", ""),
  new Democrat("Busy Philipps", "./photos/Busy_Philipps.jpg", ""),
  new Democrat("Lou Diamond Phillips", "./photos/Lou_Diamond_Phillips.jpg", ""),
  new Democrat("Robert Picardo", "./photos/Robert_Picardo.jpg", ""),
  new Democrat("Wendell Pierce", "./photos/Wendell_Pierce.jpg", ""),
  new Democrat("Oliver Platt", "./photos/Oliver_Platt.jpg", ""),
  new Democrat("Aubrey Plaza", "./photos/Aubrey_Plaza.jpg", ""),
  new Democrat("Ellen Pompeo", "./photos/Ellen_Pompeo.jpg", ""),
  new Democrat("Melissa Ponzio", "./photos/Melissa_Ponzio.jpg", ""),
  new Democrat("Jeremy Pope", "./photos/Jeremy_Pope.jpg", ""),
  new Democrat("Billy Porter", "./photos/Billy_Porter.jpg", ""),
  new Democrat("Will Poulter", "./photos/Will_Poulter.jpg", ""),
  new Democrat("Jack Quaid", "./photos/Jack_Quaid.jpg", ""),
  new Democrat("Zachary Quinto", "./photos/Zachary_Quinto.jpg", ""),
  new Democrat("Sheryl Lee Ralph", "./photos/Sheryl_Lee_Ralph.jpg", ""),
  new Democrat("Anthony Ramos", "./photos/Anthony_Ramos.jpg", ""),
  new Democrat("Andrew Rannells", "./photos/Andrew_Rannells.jpg", ""),
  new Democrat("Anthony Rapp", "./photos/Anthony_Rapp.jpg", ""),
  new Democrat("Kate Reinders", "./photos/Kate_Reinders.jpg", ""),
  new Democrat("Alysia Reiner", "./photos/Alysia_Reiner.jpg", ""),
  new Democrat("Lili Reinhart", "./photos/Lili_Reinhart.jpg", ""),
  new Democrat("Sam Richardson", "./photos/Sam_Richardson.jpg", ""),
  new Democrat("Molly Ringwald", "./photos/Molly_Ringwald.jpg", ""),
  new Democrat("Lisa Rinna", "./photos/Lisa_Rinna.jpg", ""),
  new Democrat("Julia Roberts", "./photos/Julia_Roberts.jpg", ""),
  new Democrat("Craig Robinson", "./photos/Craig_Robinson.jpg", ""),
  new Democrat("Krysta Rodriguez", "./photos/Krysta_Rodriguez.jpg", ""),
  new Democrat("Tracee Ellis Ross", "./photos/Tracee_Ellis_Ross.jpg", ""),
  new Democrat("Yolonda Ross", "./photos/Yolonda_Ross.jpg", ""),
  new Democrat("Portia de Rossi", "./photos/Portia_de_Rossi.jpg", ""),
  new Democrat("Emmy Rossum", "./photos/Emmy_Rossum.jpg", ""),
  new Democrat("Daphne Rubin-Vega", "./photos/Daphne_Rubin-Vega.jpg", ""),
  new Democrat("Mark Ruffalo", "./photos/Mark_Ruffalo.jpg", ""),
  new Democrat("Jeri Ryan", "./photos/Jeri_Ryan.jpg", ""),
  new Democrat("George Salazar", "./photos/George_Salazar.jpg", ""),
  new Democrat("Stark Sands", "./photos/Stark_Sands.jpg", ""),
  new Democrat("Ruben Santiago-Hudson", "./photos/Ruben_Santiago-Hudson.jpg", ""),
  new Democrat("Scott Turner Schofield", "./photos/Scott_Turner_Schofield.jpg", ""),
  new Democrat("Reid Scott", "./photos/Reid_Scott.jpg", ""),
  new Democrat("Christopher Sean", "./photos/Christopher_Sean.jpg", ""),
  new Democrat("Teddy Sears", "./photos/Teddy_Sears.jpg", ""),
  new Democrat("Kyra Sedgwick", "./photos/Kyra_Sedgwick.jpg", ""),
  new Democrat("Martin Sheen", "./photos/Martin_Sheen.jpg", ""),
  new Democrat("Sheetal Sheth", "./photos/Sheetal_Sheth.jpg", ""),
  new Democrat("Reshma Shetty", "./photos/Reshma_Shetty.jpg", ""),
  new Democrat("Timothy Simons", "./photos/Timothy_Simons.jpg", ""),
  new Democrat("Tiya Sircar", "./photos/Tiya_Sircar.jpg", ""),
  new Democrat("Tom Skerritt", "./photos/Tom_Skerritt.jpg", ""),
  new Democrat("Antonique Smith", "./photos/Antonique_Smith.jpg", ""),
  new Democrat("Brian Michael Smith", "./photos/Brian_Michael_Smith.jpg", ""),
  new Democrat("Octavia Spencer", "./photos/Octavia_Spencer.jpg", ""),
  new Democrat("John Stamos", "./photos/John_Stamos.jpg", ""),
  new Democrat("Kristen Stewart", "./photos/Kristen_Stewart.jpg", ""),
  new Democrat("Sharon Stone", "./photos/Sharon_Stone.jpg", ""),
  new Democrat("Raven-Symoné", "./photos/Raven-Symoné.jpg", ""),
  new Democrat("George Takei", "./photos/George_Takei.jpg", ""),
  new Democrat("Amber Tamblyn", "./photos/Amber_Tamblyn.jpg", ""),
  new Democrat("Shaina Taub", "./photos/Shaina_Taub.jpg", ""),
  new Democrat("Renée Taylor", "./photos/Renée_Taylor.jpg", ""),
  new Democrat("Bex Taylor-Klaus", "./photos/Bex_Taylor-Klaus.jpg", ""),
  new Democrat("Damian Terriquez", "./photos/Damian_Terriquez.jpg", ""),
  new Democrat("Jennifer Laura Thompson", "./photos/Jennifer_Laura_Thompson.jpg", ""),
  new Democrat("Bella Thorne", "./photos/Bella_Thorne.jpg", ""),
  new Democrat("Uma Thurman", "./photos/Uma_Thurman.jpg", ""),
  new Democrat("Ashley Tisdale", "./photos/Ashley_Tisdale.jpg", ""),
  new Democrat("Marisa Tomei", "./photos/Marisa_Tomei.jpg", ""),
  new Democrat("Tamlyn Tomita", "./photos/Tamlyn_Tomita.jpg", ""),
  new Democrat("Lily Tomlin", "./photos/Lily_Tomlin.jpg", ""),
  new Democrat("Lorraine Toussaint", "./photos/Lorraine_Toussaint.jpg", ""),
  new Democrat("John Turturro", "./photos/John_Turturro.jpg", ""),
  new Democrat("Aisha Tyler", "./photos/Aisha_Tyler.jpg", ""),
  new Democrat("Nia Vardalos", "./photos/Nia_Vardalos.jpg", ""),
  new Democrat("Nana Visitor", "./photos/Nana_Visitor.jpg", ""),
  new Democrat("Kate Walsh", "./photos/Kate_Walsh.jpg", ""),
  new Democrat("Matt Walsh", "./photos/Matt_Walsh.jpg", ""),
  new Democrat("Adrienne Warren", "./photos/Adrienne_Warren.jpg", ""),
  new Democrat("Sam Waterston", "./photos/Sam_Waterston.jpg", ""),
  new Democrat("Sigourney Weaver", "./photos/Sigourney_Weaver.jpg", ""),
  new Democrat("Denise Welch", "./photos/Denise_Welch.jpg", ""),
  new Democrat("Bradley Whitford", "./photos/Bradley_Whitford.jpg", ""),
  new Democrat("Rita Wilson", "./photos/Rita_Wilson.jpg", ""),
  new Democrat("Reese Witherspoon", "./photos/Reese_Witherspoon.jpg", ""),
  new Democrat("Deborah Ann Woll", "./photos/Deborah_Ann_Woll.jpg", ""),
  new Democrat("BD Wong", "./photos/BD_Wong.jpg", ""),
  new Democrat("Alfre Woodard", "./photos/Alfre_Woodard.jpg", ""),
  new Democrat("Jeffrey Wright", "./photos/Jeffrey_Wright.jpg", ""),
  new Democrat("Hudson Yang", "./photos/Hudson_Yang.jpg", ""),
  new Democrat("Bellamy Young", "./photos/Bellamy_Young.jpg", ""),
  new Democrat("Rachel Zegler", "./photos/Rachel_Zegler.jpg", ""),
  new Democrat("Kalen Allen", "./photos/Kalen_Allen.jpg", ""),
  new Democrat("Samantha Bee", "./photos/Samantha_Bee.jpg", ""),
  new Democrat("Joy Behar", "./photos/Joy_Behar.jpg", ""),
  new Democrat("Sandra Bernhard", "./photos/Sandra_Bernhard.jpg", ""),
  new Democrat("Alonzo Bodden", "./photos/Alonzo_Bodden.jpg", ""),
  new Democrat("Michelle Buteau", "./photos/Michelle_Buteau.jpg", ""),
  new Democrat("Drew Carey", "./photos/Drew_Carey.jpg", ""),
  new Democrat("Margaret Cho", "./photos/Margaret_Cho.jpg", ""),
  new Democrat("Stephen Colbert", "./photos/Stephen_Colbert.jpg", ""),
  new Democrat("Trae Crowder", "./photos/Trae_Crowder.jpg", ""),
  new Democrat("Larry David", "./photos/Larry_David.jpg", ""),
  new Democrat("Ellen DeGeneres", "./photos/Ellen_DeGeneres.jpg", ""),
  new Democrat("Nik Dodani", "./photos/Nik_Dodani.jpg", ""),
  new Democrat("Alex Edelman", "./photos/Alex_Edelman.jpg", ""),
  new Democrat("Ophira Eisenberg", "./photos/Ophira_Eisenberg.jpg", ""),
  new Democrat("Cedric the Entertainer", "./photos/Cedric_the_Entertainer.jpg", ""),
  new Democrat("Susie Essman", "./photos/Susie_Essman.jpg", ""),
  new Democrat("Negin Farsad", "./photos/Negin_Farsad.jpg", ""),
  new Democrat("Christian Finnegan", "./photos/Christian_Finnegan.jpg", ""),
  new Democrat("John Fugelsang", "./photos/John_Fugelsang.jpg", ""),
  new Democrat("Janeane Garofalo", "./photos/Janeane_Garofalo.jpg", ""),
  new Democrat("Illana Glazer", "./photos/Illana_Glazer.jpg", ""),
  new Democrat("Judy Gold", "./photos/Judy_Gold.jpg", ""),
  new Democrat("Dana Goldberg", "./photos/Dana_Goldberg.jpg", ""),
  new Democrat("Whoopi Goldberg", "./photos/Whoopi_Goldberg.jpg", ""),
  new Democrat("Harrison Greenbaum", "./photos/Harrison_Greenbaum.jpg", ""),
  new Democrat("Kathy Griffin", "./photos/Kathy_Griffin.jpg", ""),
  new Democrat("Gary Gulman", "./photos/Gary_Gulman.jpg", ""),
  new Democrat("Tiffany Haddish", "./photos/Tiffany_Haddish.jpg", ""),
  new Democrat("D. L. Hughley", "./photos/D._L._Hughley.jpg", ""),
  new Democrat("Laurie Kilmartin", "./photos/Laurie_Kilmartin.jpg", ""),
  new Democrat("George Lopez", "./photos/George_Lopez.jpg", ""),
  new Democrat("Al Madrigal", "./photos/Al_Madrigal.jpg", ""),
  new Democrat("Bill Maher", "./photos/Bill_Maher.jpg", ""),
  new Democrat("Marc Maron", "./photos/Marc_Maron.jpg", ""),
  new Democrat("Kumail Nanjiani", "./photos/Kumail_Nanjiani.jpg", ""),
  new Democrat("Rex Navarrete", "./photos/Rex_Navarrete.jpg", ""),
  new Democrat("Patton Oswalt", "./photos/Patton_Oswalt.jpg", ""),
  new Democrat("Rosie O'Donnell", "./photos/Rosie_O'Donnell.jpg", ""),
  new Democrat("Paula Poundstone", "./photos/Paula_Poundstone.jpg", ""),
  new Democrat("Brian Posehn", "./photos/Brian_Posehn.jpg", ""),
  new Democrat("Retta", "./photos/Retta.jpg", ""),
  new Democrat("Phoebe Robinson", "./photos/Phoebe_Robinson.jpg", ""),
  new Democrat("Chris Rock", "./photos/Chris_Rock.jpg", ""),
  new Democrat("Paul Scheer", "./photos/Paul_Scheer.jpg", ""),
  new Democrat("Jana Schmieding", "./photos/Jana_Schmieding.jpg", ""),
  new Democrat("Cecily Strong", "./photos/Cecily_Strong.jpg", ""),
  new Democrat("Wanda Sykes", "./photos/Wanda_Sykes.jpg", ""),
  new Democrat("Robin Thede", "./photos/Robin_Thede.jpg", ""),
  new Democrat("Kenan Thompson", "./photos/Kenan_Thompson.jpg", ""),
  new Democrat("Baratunde Thurston", "./photos/Baratunde_Thurston.jpg", ""),
  new Democrat("Jimmy Tingle", "./photos/Jimmy_Tingle.jpg", ""),
  new Democrat("Taylor Tomlinson", "./photos/Taylor_Tomlinson.jpg", ""),
  new Democrat("George Wallace", "./photos/George_Wallace.jpg", ""),
  new Democrat("Lisa Ann Walter", "./photos/Lisa_Ann_Walter.jpg", ""),
  new Democrat("Roy Wood Jr.", "./photos/Roy_Wood_Jr..jpg", ""),
  new Democrat("Gracie Abrams", "./photos/Gracie_Abrams.jpg", ""),
  new Democrat("Marc Anthony", "./photos/Marc_Anthony.jpg", ""),
  new Democrat("Jack Antonoff", "./photos/Jack_Antonoff.jpg", ""),
  new Democrat("Emily Armstrong", "./photos/Emily_Armstrong.jpg", ""),
  new Democrat("Sebastian Bach", "./photos/Sebastian_Bach.jpg", ""),
  new Democrat("Joan Baez", "./photos/Joan_Baez.jpg", ""),
  new Democrat("Chloe Bailey", "./photos/Chloe_Bailey.jpg", ""),
  new Democrat("Halle Bailey", "./photos/Halle_Bailey.jpg", ""),
  new Democrat("Sara Bareilles", "./photos/Sara_Bareilles.jpg", ""),
  new Democrat("Lance Bass", "./photos/Lance_Bass.jpg", ""),
  new Democrat("Sunshine Becker", "./photos/Sunshine_Becker.jpg", ""),
  new Democrat("Matt Berninger", "./photos/Matt_Berninger.jpg", ""),
  new Democrat("Elvin Bishop", "./photos/Elvin_Bishop.jpg", ""),
  new Democrat("Justin Vivian Bond", "./photos/Justin_Vivian_Bond.jpg", ""),
  new Democrat("Dee Dee Bridgewater", "./photos/Dee_Dee_Bridgewater.jpg", ""),
  new Democrat("Ann Hampton Callaway", "./photos/Ann_Hampton_Callaway.jpg", ""),
  new Democrat("Rosanne Cash", "./photos/Rosanne_Cash.jpg", ""),
  new Democrat("Felix Cavaliere", "./photos/Felix_Cavaliere.jpg", ""),
  new Democrat("Charli XCX", "./photos/Charli_XCX.jpg", ""),
  new Democrat("Cher", "./photos/Cher.jpg", ""),
  new Democrat("Wayne Coyne", "./photos/Wayne_Coyne.jpg", ""),
  new Democrat("Lana Del Rey", "./photos/Lana_Del_Rey.jpg", ""),
  new Democrat("Aaron Dessner", "./photos/Aaron_Dessner.jpg", ""),
  new Democrat("Ricky Dillard", "./photos/Ricky_Dillard.jpg", ""),
  new Democrat("Sheila E.", "./photos/Sheila_E..jpg", ""),
  new Democrat("Billie Eilish", "./photos/Billie_Eilish.jpg", ""),
  new Democrat("Lady Gaga", "./photos/Lady_Gaga.jpg", ""),
  new Democrat("David Gans", "./photos/David_Gans.jpg", ""),
  new Democrat("Selena Gomez", "./photos/Selena_Gomez.jpg", ""),
  new Democrat("Josh Groban", "./photos/Josh_Groban.jpg", ""),
  new Democrat("Mickey Guyton", "./photos/Mickey_Guyton.jpg", ""),
  new Democrat("Malynda Hale", "./photos/Malynda_Hale.jpg", ""),
  new Democrat("Todrick Hall", "./photos/Todrick_Hall.jpg", ""),
  new Democrat("Magos Herrera", "./photos/Magos_Herrera.jpg", ""),
  new Democrat("Janis Ian", "./photos/Janis_Ian.jpg", ""),
  new Democrat("Jason Isbell", "./photos/Jason_Isbell.jpg", ""),
  new Democrat("Joan Jett", "./photos/Joan_Jett.jpg", ""),
  new Democrat("Jack Johnson", "./photos/Jack_Johnson.jpg", ""),
  new Democrat("Gary Jules", "./photos/Gary_Jules.jpg", ""),
  new Democrat("Noah Kahan", "./photos/Noah_Kahan.jpg", ""),
  new Democrat("Marc Anthony", "./photos/Marc_Anthony.jpg", ""),
  new Democrat("Kesha", "./photos/Kesha.jpg", ""),
  new Democrat("Alicia Keys", "./photos/Alicia_Keys.jpg", ""),
  new Democrat("Carole King", "./photos/Carole_King.jpg", ""),
  new Democrat("Patti LaBelle", "./photos/Patti_LaBelle.jpg", ""),
  new Democrat("Lachi", "./photos/Lachi.jpg", ""),
  new Democrat("Laufey", "./photos/Laufey.jpg", ""),
  new Democrat("Cyndi Lauper", "./photos/Cyndi_Lauper.jpg", ""),
  new Democrat("John Legend", "./photos/John_Legend.jpg", ""),
  new Democrat("Lisa Loeb", "./photos/Lisa_Loeb.jpg", ""),
  new Democrat("Jennifer Lopez", "./photos/Jennifer_Lopez.jpg", ""),
  new Democrat("Demi Lovato", "./photos/Demi_Lovato.jpg", ""),
  new Democrat("Madonna", "./photos/Madonna.jpg", ""),
  new Democrat("Martie Maguire", "./photos/Martie_Maguire.jpg", ""),
  new Democrat("Natalie Maines", "./photos/Natalie_Maines.jpg", ""),
  new Democrat("Ricky Martin", "./photos/Ricky_Martin.jpg", ""),
  new Democrat("Tom Maxwell", "./photos/Tom_Maxwell.jpg", ""),
  new Democrat("AJ McLean", "./photos/AJ_McLean.jpg", ""),
  new Democrat("Natalie Merchant", "./photos/Natalie_Merchant.jpg", ""),
  new Democrat("AJ Michalka", "./photos/AJ_Michalka.jpg", ""),
  new Democrat("Aly Michalka", "./photos/Aly_Michalka.jpg", ""),
  new Democrat("Joni Mitchell", "./photos/Joni_Mitchell.jpg", ""),
  new Democrat("Moby", "./photos/Moby.jpg", ""),
  new Democrat("Janelle Monáe", "./photos/Janelle_Monáe.jpg", ""),
  new Democrat("Mandy Moore", "./photos/Mandy_Moore.jpg", ""),
  new Democrat("Maren Morris", "./photos/Maren_Morris.jpg", ""),
  new Democrat("Alanis Morissette", "./photos/Alanis_Morissette.jpg", ""),
  new Democrat("Graham Nash", "./photos/Graham_Nash.jpg", ""),
  new Democrat("Naturi Naughton", "./photos/Naturi_Naughton.jpg", ""),
  new Democrat("Willie Nelson", "./photos/Willie_Nelson.jpg", ""),
  new Democrat("Stevie Nicks", "./photos/Stevie_Nicks.jpg", ""),
  new Democrat("Coleen Nolan", "./photos/Coleen_Nolan.jpg", ""),
  new Democrat("Finneas O'Connell", "./photos/Finneas_O'Connell.jpg", ""),
  new Democrat("Don Omar", "./photos/Don_Omar.jpg", ""),
  new Democrat("Justin Vivian Bond", "./photos/Justin_Vivian_Bond.jpg", ""),
  new Democrat("Glen Phillips", "./photos/Glen_Phillips.jpg", ""),
  new Democrat("Chris Pierce", "./photos/Chris_Pierce.jpg", ""),
  new Democrat("Steve Poltz", "./photos/Steve_Poltz.jpg", ""),
  new Democrat("Margo Price", "./photos/Margo_Price.jpg", ""),
  new Democrat("Addison Rae", "./photos/Addison_Rae.jpg", ""),
  new Democrat("Gretta Ray", "./photos/Gretta_Ray.jpg", ""),
  new Democrat("Eric Roberson", "./photos/Eric_Roberson.jpg", ""),
  new Democrat("Smokey Robinson", "./photos/Smokey_Robinson.jpg", ""),
  new Democrat("Olivia Rodrigo", "./photos/Olivia_Rodrigo.jpg", ""),
  new Democrat("Linda Ronstadt", "./photos/Linda_Ronstadt.jpg", ""),
  new Democrat("Maggie Rose", "./photos/Maggie_Rose.jpg", ""),
  new Democrat("Kelly Rowland", "./photos/Kelly_Rowland.jpg", ""),
  new Democrat("Sia", "./photos/Sia.jpg", ""),
  new Democrat("Nancy Sinatra", "./photos/Nancy_Sinatra.jpg", ""),
  new Democrat("Alex Skolnick", "./photos/Alex_Skolnick.jpg", ""),
  new Democrat("Patti Smith", "./photos/Patti_Smith.jpg", ""),
  new Democrat("Donita Sparks", "./photos/Donita_Sparks.jpg", ""),
  new Democrat("Brittney Spencer", "./photos/Brittney_Spencer.jpg", ""),
  new Democrat("Bruce Springsteen", "./photos/Bruce_Springsteen.jpg", ""),
  new Democrat("Mavis Staples", "./photos/Mavis_Staples.jpg", ""),
  new Democrat("Rod Stewart", "./photos/Rod_Stewart.jpg", ""),
  new Democrat("Michael Stipe", "./photos/Michael_Stipe.jpg", ""),
  new Democrat("Emily Strayer", "./photos/Emily_Strayer.jpg", ""),
  new Democrat("Barbra Streisand", "./photos/Barbra_Streisand.jpg", ""),
  new Democrat("Aaron Lee Tasjan", "./photos/Aaron_Lee_Tasjan.jpg", ""),
  new Democrat("James Taylor", "./photos/James_Taylor.jpg", ""),
  new Democrat("Justin Tranter", "./photos/Justin_Tranter.jpg", ""),
  new Democrat("Corin Tucker", "./photos/Corin_Tucker.jpg", ""),
  new Democrat("Dara Tucker", "./photos/Dara_Tucker.jpg", ""),
  new Democrat("Usher", "./photos/Usher.jpg", ""),
  new Democrat("Justin Vernon", "./photos/Justin_Vernon.jpg", ""),
  new Democrat("Jessica Vosk", "./photos/Jessica_Vosk.jpg", ""),
  new Democrat("Rufus Wainwright", "./photos/Rufus_Wainwright.jpg", ""),
  new Democrat("Joe Walsh ", "./photos/Joe_Walsh_.jpg", ""),
  new Democrat("Dionne Warwick", "./photos/Dionne_Warwick.jpg", ""),
  new Democrat("Suki Waterhouse", "./photos/Suki_Waterhouse.jpg", ""),
  new Democrat("Bob Weir", "./photos/Bob_Weir.jpg", ""),
  new Democrat("Jack White", "./photos/Jack_White.jpg", ""),
  new Democrat("Betty Who", "./photos/Betty_Who.jpg", ""),
  new Democrat("Hayley Williams", "./photos/Hayley_Williams.jpg", ""),
  new Democrat("Lucinda Williams", "./photos/Lucinda_Williams.jpg", ""),
  new Democrat("Remi Wolf", "./photos/Remi_Wolf.jpg", ""),
  new Democrat("Stevie Wonder", "./photos/Stevie_Wonder.jpg", ""),
  new Democrat("Neil Young", "./photos/Neil_Young.jpg", ""),
  new Democrat("Nicole Zuraitis", "./photos/Nicole_Zuraitis.jpg", ""),
  new Democrat("St. Vincent", "./photos/St._Vincent.jpg", ""),

];

// Add Celebrities Supporting Republican Party into this array
// Republican(Name, PhotoLink, ReferenceLink)
let republicans = [
  new Republican("Elon Musk", "./photos/Elon_Musk.jpg", "https://www.independent.co.uk/arts-entertainment/films/news/trump-celebrity-endorsements-buzz-aldrin-elon-musk-b2638749.html"),
  new Republican("Jon Voight", "./photos/Jon_Voight.jpg", "https://variety.com/2024/film/news/jon-voight-trump-support-israel-palestine-angelina-jolie-1236080058/"),
  new Republican("Kelsey Grammer", "./photos/Kelsey_Grammer.jpg", "https://ew.com/kelsey-grammer-interview-cut-after-voicing-support-for-donald-trump-8410830"),
  new Republican("Dennis Rodman", "./photos/Dennis_Rodman.jpg", "https://www.cnn.com/2018/06/11/asia/rodman-trump-kim-summit-intl/index.html"),
  new Republican("Antonio Sabato Jr.", "./photos/Antonio_Sabato_Jr..jpg", "https://www.scmp.com/magazines/style/entertainment/article/3269938/meet-antonio-sabato-jr-who-was-cancelled-hollywood-supporting-donald-trump-general-hospital-actor"),
  new Republican("Mike Tyson", "./photos/Mike_Tyson.jpg", "https://www.sportskeeda.com/mma/news-mike-tyson-endorses-donald-trump-ahead-2024-us-elections-i-agree-sh-t"),
  new Republican("Clint Eastwood", "./photos/Clint_Eastwood.jpg", "https://www.breckell.uk/nowstream1/who-does-clint-eastwood-support-for-president-in-2024.html"),
  new Republican("Larry the Cable Guy", "./photos/Larry_the_Cable_Guy.jpg", "https://easterislandtourism.com/resonatenews3/is-larry-the-cable-guy-a-trump-supporter.html"),
  new Republican("Victoria Jackson", "./photos/Victoria_Jackson.jpg", "https://www.independent.co.uk/arts-entertainment/films/news/trump-celebrity-endorsements-buzz-aldrin-elon-musk-b2638749.html"),
  new Republican("Mel Gibson", "./photos/Mel_Gibson.jpg", ""),
  new Republican("Chuck Norris", "./photos/Chuck_Norris.jpg", ""),
  new Republican("James Woods", "./photos/James_Woods.jpg", ""),
  new Republican("Caitlyn Jenner", "./photos/Caitlyn_Jenner.jpg", ""),
  new Republican("Burt Reynolds", "./photos/Burt_Reynolds.jpg", ""),
  new Republican("Pat Sajak", "./photos/Pat_Sajak.jpg", ""),
  new Republican("Eric Roberts", "./photos/Eric_Roberts.jpg", ""),
  new Republican("Jesse Metcalfe", "./photos/Jesse_Metcalfe.jpg", ""),
  new Republican("Alicia Silverstone", "./photos/Alicia_Silverstone.jpg", ""),
  new Republican("Natalie Maines", "./photos/Natalie_Maines.jpg", ""),
  new Republican("Kurt Russell", "./photos/Kurt_Russell.jpg", ""),
  new Republican("Stephen Baldwin", "./photos/Stephen_Baldwin.jpg", ""),
  new Republican("Tucker Carlson", "./photos/Tucker_Carlson.jpg", ""),
  new Republican("Patrick M. Byrne", "./photos/Patrick_M._Byrne.jpg", ""),
  new Republican("John Catsimatidis", "./photos/John_Catsimatidis.jpg", ""),
  new Republican("Ryan Cohen", "./photos/Ryan_Cohen.jpg", ""),
  new Republican("Mike Lindell", "./photos/Mike_Lindell.jpg", ""),
  new Republican("Jim McIngvale", "./photos/Jim_McIngvale.jpg", ""),
  new Republican("Larry Ellison", "./photos/Larry_Ellison.jpg", ""),
  new Republican("Jacob Helberg", "./photos/Jacob_Helberg.jpg", ""),
  new Republican("Jeremy Kauffman", "./photos/Jeremy_Kauffman.jpg", ""),
  new Republican("Joe Lonsdale", "./photos/Joe_Lonsdale.jpg", ""),
  new Republican("Palmer Luckey", "./photos/Palmer_Luckey.jpg", ""),
  new Republican("Jason Miller", "./photos/Jason_Miller.jpg", ""),
  new Republican("Nate Morris", "./photos/Nate_Morris.jpg", ""),
  new Republican("Robert J. Shillman", "./photos/Robert_J._Shillman.jpg", ""),
  new Republican("Thomas Siebel", "./photos/Thomas_Siebel.jpg", ""),
  new Republican("Naval Ravikant", "./photos/Naval_Ravikant.jpg", ""),
  new Republican("Peter Thiel", "./photos/Peter_Thiel.jpg", ""),
  new Republican("Ronnie Barrett", "./photos/Ronnie_Barrett.jpg", ""),
  new Republican("Joe Exotic", "./photos/Joe_Exotic.jpg", ""),
  new Republican("Steve Forbes", "./photos/Steve_Forbes.jpg", ""),
  new Republican("Rick Harrison", "./photos/Rick_Harrison.jpg", ""),
  new Republican("Charles Herbster", "./photos/Charles_Herbster.jpg", ""),
  new Republican("Perry Johnson", "./photos/Perry_Johnson.jpg", ""),
  new Republican("Adam Kidan", "./photos/Adam_Kidan.jpg", ""),
  new Republican("Shalabh Kumar", "./photos/Shalabh_Kumar.jpg", ""),
  new Republican("Tim Michels", "./photos/Tim_Michels.jpg", ""),
  new Republican("Bernie Moreno", "./photos/Bernie_Moreno.jpg", ""),
  new Republican("Vivek Ramaswamy", "./photos/Vivek_Ramaswamy.jpg", ""),
  new Republican("Hilary Geary Ross", "./photos/Hilary_Geary_Ross.jpg", ""),
  new Republican("John Schnatter", "./photos/John_Schnatter.jpg", ""),
  new Republican("Sajid Tarar", "./photos/Sajid_Tarar.jpg", ""),
  new Republican("Donald Trump Jr.", "./photos/Donald_Trump_Jr..jpg", ""),
  new Republican("Eric Trump", "./photos/Eric_Trump.jpg", ""),
  new Republican("Tiffany Trump", "./photos/Tiffany_Trump.jpg", ""),
  new Republican("Scott Baio", "./photos/Scott_Baio.jpg", ""),
  new Republican("Roseanne Barr", "./photos/Roseanne_Barr.jpg", ""),
  new Republican("Russell Brand", "./photos/Russell_Brand_(co-endorsed_with_Robert_F._Kennedy_Jr.).jpg", ""),
  new Republican("Martha Byrne", "./photos/Martha_Byrne.jpg", ""),
  new Republican("Dean Cain", "./photos/Dean_Cain.jpg", ""),
  new Republican("Gina Carano", "./photos/Gina_Carano.jpg", ""),
  new Republican("Jim Caviezel", "./photos/Jim_Caviezel.jpg", ""),
  new Republican("Michael Copon", "./photos/Michael_Copon.jpg", ""),
  new Republican("Robert Davi", "./photos/Robert_Davi.jpg", ""),
  new Republican("Vincent Gallo", "./photos/Vincent_Gallo.jpg", ""),
  new Republican("Zachary Levi (co-endorsed with Robert F. Kennedy Jr.)", "./photos/Zachary_Levi_(co-endorsed_with_Robert_F._Kennedy_Jr.).jpg", ""),
  new Republican("Taryn Manning", "./photos/Taryn_Manning.jpg", ""),
  new Republican("Marla Maples (Trump's former wife)", "./photos/Marla_Maples_(Trump's_former_wife).jpg", ""),
  new Republican("Dasha Nekrasova", "./photos/Dasha_Nekrasova.jpg", ""),
  new Republican("Susan Olsen", "./photos/Susan_Olsen.jpg", ""),
  new Republican("Dennis Quaid", "./photos/Dennis_Quaid.jpg", ""),
  new Republican("Randy Quaid", "./photos/Randy_Quaid.jpg", ""),
  new Republican("John Ratzenberger", "./photos/John_Ratzenberger.jpg", ""),
  new Republican("Antonio Sabàto Jr.", "./photos/Antonio_Sabàto_Jr..jpg", ""),
  new Republican("John Schneider", "./photos/John_Schneider.jpg", ""),
  new Republican("Rob Schneider", "./photos/Rob_Schneider.jpg", ""),
  new Republican("Kevin Sorbo", "./photos/Kevin_Sorbo.jpg", ""),
  new Republican("Kristy Swanson", "./photos/Kristy_Swanson.jpg", ""),
  new Republican("Jamal Trulove", "./photos/Jamal_Trulove.jpg", ""),
  new Republican("Holly Valance", "./photos/Holly_Valance.jpg", ""),
  new Republican("Eduardo Verástegui", "./photos/Eduardo_Verástegui.jpg", ""),
  new Republican("Chuck Zito", "./photos/Chuck_Zito.jpg", ""),
  new Republican("Savannah Chrisley", "./photos/Savannah_Chrisley.jpg", ""),
  new Republican("Adrianne Curry", "./photos/Adrianne_Curry.jpg", ""),
  new Republican("Paula Deen", "./photos/Paula_Deen.jpg", ""),
  new Republican("Vinny Guadagnino", "./photos/Vinny_Guadagnino.jpg", ""),
  new Republican("Phil McGraw", "./photos/Phil_McGraw.jpg", ""),
  new Republican("Mehmet Oz", "./photos/Mehmet_Oz.jpg", ""),
  new Republican("Santino Rice", "./photos/Santino_Rice.jpg", ""),
  new Republican("Phil Robertson", "./photos/Phil_Robertson.jpg", ""),
  new Republican("Amber Rose", "./photos/Amber_Rose.jpg", ""),
  new Republican("Anuel AA", "./photos/Anuel_AA.jpg", ""),
  new Republican("Trace Adkins", "./photos/Trace_Adkins.jpg", ""),
  new Republican("Jason Aldean", "./photos/Jason_Aldean.jpg", ""),
  new Republican("Azealia Banks", "./photos/Azealia_Banks.jpg", ""),
  new Republican("Benny the Butcher", "./photos/Benny_the_Butcher.jpg", ""),
  new Republican("Kodak Black", "./photos/Kodak_Black.jpg", ""),
  new Republican("Bleona", "./photos/Bleona.jpg", ""),
  new Republican("Jonathan Cain", "./photos/Jonathan_Cain.jpg", ""),
  new Republican("Naked Cowboy", "./photos/Naked_Cowboy.jpg", ""),
  new Republican("Ice Cube", "./photos/Ice_Cube.jpg", ""),
  new Republican("Billy Ray Cyrus", "./photos/Billy_Ray_Cyrus.jpg", ""),
  new Republican("DaBaby", "./photos/DaBaby.jpg", ""),
  new Republican("John Dolmayan", "./photos/John_Dolmayan.jpg", ""),
  new Republican("42 Dugg", "./photos/42_Dugg.jpg", ""),
  new Republican("Sean Feucht", "./photos/Sean_Feucht.jpg", ""),
  new Republican("Waka Flocka Flame", "./photos/Waka_Flocka_Flame.jpg", ""),
  new Republican("Fivio Foreign", "./photos/Fivio_Foreign.jpg", ""),
  new Republican("Sheff G", "./photos/Sheff_G.jpg", ""),
  new Republican("Lee Greenwood", "./photos/Lee_Greenwood.jpg", ""),
  new Republican("Sleepy Hallow", "./photos/Sleepy_Hallow.jpg", ""),
  new Republican("Lord Jamar", "./photos/Lord_Jamar.jpg", ""),
  new Republican("Chris Janson", "./photos/Chris_Janson.jpg", ""),
  new Republican("Kerry Katona", "./photos/Kerry_Katona.jpg", ""),
  new Republican("Brian Kelley", "./photos/Brian_Kelley.jpg", ""),
  new Republican("Swae Lee", "./photos/Swae_Lee.jpg", ""),
  new Republican("Aaron Lewis", "./photos/Aaron_Lewis.jpg", ""),
  new Republican("Justin Moore", "./photos/Justin_Moore.jpg", ""),
  new Republican("Ted Nugent", "./photos/Ted_Nugent.jpg", ""),
  new Republican("Martin O'Donnell", "./photos/Martin_O'Donnell.jpg", ""),
  new Republican("Lil Pump", "./photos/Lil_Pump.jpg", ""),
  new Republican("Justin Quiles", "./photos/Justin_Quiles.jpg", ""),
  new Republican("John Rich", "./photos/John_Rich.jpg", ""),
  new Republican("Kid Rock", "./photos/Kid_Rock.jpg", ""),
  new Republican("Frank Stallone", "./photos/Frank_Stallone.jpg", ""),
  new Republican("Topher", "./photos/Topher.jpg", ""),
  new Republican("Travis Tritt", "./photos/Travis_Tritt.jpg", ""),
  new Republican("Trick Trick", "./photos/Trick_Trick.jpg", ""),
  new Republican("Icewear Vezzo", "./photos/Icewear_Vezzo.jpg", ""),
  new Republican("Lil Wayne", "./photos/Lil_Wayne.jpg", ""),
  new Republican("Chris Webby", "./photos/Chris_Webby.jpg", ""),
  new Republican("Kanye West", "./photos/Kanye_West.jpg", ""),
  new Republican("Hank Williams Jr.", "./photos/Hank_Williams_Jr..jpg", ""),
  new Republican("Gretchen Wilson", "./photos/Gretchen_Wilson.jpg", ""),
  new Republican("Jaguar Wright", "./photos/Jaguar_Wright.jpg", ""),
  new Republican("Enes Kanter Freedom", "./photos/Enes_Kanter_Freedom.jpg", ""),
  new Republican("Royce White", "./photos/Royce_White.jpg", ""),
  new Republican("Joe Craft", "./photos/Joe_Craft.jpg", ""),
  new Republican("Dan K. Eberhart", "./photos/Dan_K._Eberhart.jpg", ""),
  new Republican("Harold Hamm", "./photos/Harold_Hamm.jpg", ""),
  new Republican("Jeffery Hildebrand", "./photos/Jeffery_Hildebrand.jpg", ""),
  new Republican("Vicki Hollub", "./photos/Vicki_Hollub.jpg", ""),
  new Republican("Kelcy Warren", "./photos/Kelcy_Warren.jpg", ""),
]

add_celebrities_to_container(democrats, "democrats-image-container");
add_celebrities_to_container(republicans, "republicans-image-container");


let position_relative = document.querySelectorAll('.position-relative');

position_relative.forEach(item => {
    item.addEventListener('mouseover', event => {
        const caption = item.querySelector('.position-absolute');
        caption.classList.remove('d-none');
    });
    item.addEventListener('mouseleave', event => {
        const caption = item.querySelector('.position-absolute');
        caption.classList.add('d-none');
    });
});
